/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Gladiator.glb -T 
Files: Gladiator.glb [66.66MB] > /Users/zihongchen/HackG/FRC-Website/public/models/Gladiator-transformed.glb [11.6MB] (83%)
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Gladiator(props) {
  const { nodes, materials } = useGLTF('/models/Gladiator-transformed.glb')
  useEffect(() => {
    Object.values(materials).forEach(material => {
      material.precision = 'lowp'
      
    })
  }, [materials])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Solid1.geometry} material={materials.PaletteMaterial001} position={[0.039, 0.046, -0.015]} rotation={[-Math.PI / 2, 1.029, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Solid1_1.geometry} material={materials.FoilGold} position={[0.039, 0.043, -0.01]} rotation={[0, 0, -1.687]} scale={0.01} />
      <mesh geometry={nodes.Solid1_2.geometry} material={materials.PaletteMaterial002} position={[0.179, 0.046, -0.031]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.Solid1_3.geometry} material={materials.CarbonFiber1} position={[-0.091, -0.156, 0.248]} rotation={[0.293, 0.605, -2.058]} scale={0.01} />
      <mesh geometry={nodes.Solid4.geometry} material={materials.PaletteMaterial003} position={[0.048, 0.004, 0.122]} rotation={[0.157, -1.57, -2.984]} scale={0.01} />
      <mesh geometry={nodes.Solid3.geometry} material={materials.PaletteMaterial004} position={[0.097, -0.243, 0.086]} rotation={[Math.PI / 2, 0.495, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Solid3_1.geometry} material={materials.PaletteMaterial005} position={[0.132, -0.246, 0.176]} rotation={[0, 0, Math.PI / 2]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/Gladiator-transformed.glb')
